### ISSUE TITLE
Different domains and secret keys?

### ISSUE THREAD

**Issue by squaddie** [Data33/laravel-mailgun#1]
Hi! Is it possible to send from multiple domains with different secret keys?

For example send msg A from domain and secret key A, and msg B with domain and secret key B.

**Comment by Data33** [comment]
Not currently, unless you check out the example `Usage without Laravel`.
In that case, you could pass the different keys directly to the transporter before sending
Maybe in the future, I might add support for sending from multiple mailgun accounts :)
